APP_NAME=autopulse-crm
INSTANCE_TYPE=free

services:
  - name: autopulse-crm-backend
    type: web
    git:
      repository: github.com/Jagannath-007/motoproj
      branch: main
    build:
      buildpack:
        build_command: "cd backend && npm install"
        run_command: "node backend/src/server.js"
    ports:
      - port: 8000
        protocol: http
    routes:
      - path: /
        port: 8000
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"
      - key: FRONTEND_URL
        value: https://autopulse-crm.wasmer.app
    instance_type: free
    regions:
      - fra
    scaling:
      min: 1
      max: 1
